keywords:
  - name: Coxa de Frango
  # - name: Tomate
  # - name: Molho de tomate
  # - name: Feijão Preto
  # - name: Shampoo
  # - name: Refrigerante
  # - name: Limão
  # - name: Cebola
  # - name: Detergente
  # - name: Macarrão Tipo 8
  # - name: Alcatra
  # - name: Maçã
  # - name: Feijão Carioca
  # - name: Alface
  # - name: Pasta dente
  # - name: Pão de Forma
  # - name: Pasta de dente
  # - name: Banana
  # - name: Sal
  # - name: Álcool
  # - name: Filé de Merluza
  # - name: Ovo
  # - name: Sabão em Pó
  # - name: Coxão Mole
  # - name: Alho
  # - name: Margarina
  # - name: Achocolatado
  # - name: Batata
  # - name: Tilapia
  # - name: Sabonete
  # - name: Papel higiênico
  # - name: Bisteca
  # - name: Chocolate
  # - name: Peito de Frango
  # - name: Arroz
  # - name: Laranja
  # - name: Óleo
  # - name: Café
  # - name: Leite
  # - name: Pernil
  # - name: Açucar
  # - name: Papel Toalha
